### PR TITLE
chlore: Upgrade Node.js version

### PR DESCRIPTION
**Pull request by lionel22**
## Description

Upgrade Node.js version
## Motivation and Context

Node.js 12 actions are deprecated

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by srisudarsan** [comment]
Hello @lionel22 Thanks for opening this PR for us. 

Hello Maintainers @wfg @tsmithv11 @thecanadianroot @robert14-els,Can some one please review this change and help us merge.

This change references https://github.com/PaloAltoNetworks/prisma-cloud-scan/pull/21

**Comment by thecanadianroot** [comment]
@srisudarsan It's been updated to node16 on my fork since october and has been working fine within my organization since then. I had to put a rush on it and couldn't wait and was busy, so I didn't have time to open up a pull request here. I've also updated GitHub Dependencies in order to fix `set-output` being deprecated.

**Comment by srisudarsan** [comment]
> @srisudarsan It's been updated to node16 on my fork since october and has been working fine within my organization since then. I had to put a rush on it and couldn't wait and was busy, so I didn't have time to open up a pull request here. I've also updated GitHub Dependencies in order to fix `set-output` being deprecated.

This is great, can you please help us get this PR opened so that we can tackle both of the deprecations at once ?

**Comment by thecanadianroot** [comment]
> > @srisudarsan It's been updated to node16 on my fork since october and has been working fine within my organization since then. I had to put a rush on it and couldn't wait and was busy, so I didn't have time to open up a pull request here. I've also updated GitHub Dependencies in order to fix `set-output` being deprecated.
> 
> This is great, can you please help us get this PR opened so that we can tackle both of the deprecations at once ?

Please see https://github.com/PaloAltoNetworks/prisma-cloud-scan/pull/23

**Comment by wfg** [comment]
#23 has been merged.

**Pull request closed without merging**
