### PR TITLE
fix: GitHub Actions deprecations

### PR DESCRIPTION
**Pull request by thecanadianroot**
## Description

Updated GitHub Action node version to 16 since 12 is now deprecated.
Updated NPM dependencies in order to fix `set-ouput` deprecation from GitHub Actions.
Added DOCKER_HOST environment variable (DOCKER_ADDRESS takes priority over DOCKER_HOST)

## Motivation and Context

In early 2023, it might break people's workflow since GitHub Actions deprecated features are scheduled to be removed.

## How Has This Been Tested?

Changes were made a couple of weeks ago on my fork and works fine within my organization.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by pexa-srisudarsan** [comment]
Thanks a lot @thecanadianroot , @wfg and maintainers, awaiting your review on this.This change will solve us a lot of noise in our CI pipelines.

**Comment by srisudarsan** [comment]
Hello @thecanadianroot @wfg , Can you please look at this PR and provide inputs to merge ?

**Comment by wfg** [comment]
@thecanadianroot Can you change index.js back to 2-space indentation? It should be good to merge once that is done.

**Comment by thecanadianroot** [comment]
@wfg Yes, sure, it's done.

**Pull request merged**
